application: mrloop-website
version: 1
runtime: python
api_version: 1
 
handlers:
# Accessing URL '/' on the site should show the public/index.html file
- url: /
  static_files: www/index.html
  upload: www/index.html

# Accessing anything under '/' (i.e. any URL at all) should return that page from folder public 
- url: /
  static_dir: www
